from PySide2.QtWidgets import QWidget, QMainWindow
from PySide2.QtGui import QIcon

def GetQMaxMainWindow() -> QMainWindow: ...
def DisableMaxAcceleratorsOnFocus(
    widget: QWidget, disableMaxAccelerators: bool
) -> None: ...
def LoadMaxMultiResIcon(path: str) -> QIcon: ...
